### ISSUE TITLE
Last photo preview does not update when the photo is deleted. Crashes app when viewed

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/Camera#12]
1. Take photo
2. Delete from gallery
3. Deleted photo stays in preview and crashes the app if you try to view it

**Comment by thestinger** [comment]
This should be fixed now.

**Comment by jorgeluiscarrillo** [comment]
This fixes the crash and throws an error message instead, but the photo preview is still not being cleared. The preview should be updated with the previous photo or be cleared if no photos exist.
